version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:5002"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
